# [퀴즈1] 직교여공간

## 풀이

**정답: $(0, 0, 1)$**

---

### 직교여공간의 정의

강의자료 51페이지에 따르면, $W$의 직교여공간은 다음과 같이 정의됩니다:

$$W^{\perp} = \{\mathbf{v} \in \mathbb{R}^n \mid \mathbf{v} \perp \mathbf{w},\ \forall \mathbf{w} \in W\}$$

즉, $W$의 모든 원소와 내적이 0인 벡터들의 집합입니다.

---

### W의 기저 파악

$$W = \text{Span}\{(1,0,0),\ (1,1,0)\}$$

$W$는 두 벡터로 생성되는 부분공간입니다. $W$의 임의의 원소 $\mathbf{w}$는:

$$\mathbf{w} = s(1,0,0) + t(1,1,0) = (s+t,\ t,\ 0)$$

---

### 직교여공간의 원소 조건 설정

$\mathbf{v} = (a, b, c) \in W^{\perp}$이 되려면, $W$의 **모든 기저 벡터**와 내적이 0이어야 합니다 (기저와의 직교성만 확인하면 충분).

**조건 1:** $(1,0,0)$과 직교
$$\langle (a,b,c),\ (1,0,0) \rangle = a = 0$$

**조건 2:** $(1,1,0)$과 직교
$$\langle (a,b,c),\ (1,1,0) \rangle = a + b = 0$$

---

### 연립방정식 풀기

$$\begin{cases} a = 0 \\ a + b = 0 \end{cases}$$

1번 식에서 $a = 0$, 이를 2번 식에 대입하면 $b = 0$.

$c$는 자유변수이므로:

$$W^{\perp} = \{(0, 0, c) \mid c \in \mathbb{R}\} = \text{Span}\{(0,0,1)\}$$

---

### 보기 검증

각 선택지가 $W^{\perp}$의 원소인지 확인합니다:

- $(2,1,0)$: $\langle(2,1,0),(1,0,0)\rangle = 2 \neq 0$, $\langle(2,1,0),(1,1,0)\rangle = 3 \neq 0$ → 오답

- $(0,1,0)$: $\langle(0,1,0),(1,0,0)\rangle = 0$, $\langle(0,1,0),(1,1,0)\rangle = 1 \neq 0$ → 오답

- $(0,0,1)$: $\langle(0,0,1),(1,0,0)\rangle = 0$, $\langle(0,0,1),(1,1,0)\rangle = 0$ → **정답**

- $(-2,1,3)$: $\langle(-2,1,3),(1,0,0)\rangle = -2 \neq 0$, $\langle(-2,1,3),(1,1,0)\rangle = -1 \neq 0$ → 오답

---



In [4]:
import numpy as np

# W = Span{(1, 0, 0), (1, 1, 0)}
# 두 생성 벡터
w1 = np.array([1, 0, 0])  # 첫 번째 기저벡터
w2 = np.array([1, 1, 0])  # 두 번째 기저벡터

# 정의 4.16 개념을 보면, 직교여공간의 원소가 되려면
# - w의 모든 기저벡터와 내적이 0이어야 함
candidates = {
    "(2,1,0)":  np.array([2, 1, 0]),    # 보기 1
    "(0,1,0)":  np.array([0, 1, 0]),    # 보기 2
    "(0,0,1)":  np.array([0, 0, 1]),    # 보기 3
    "(-2,1,3)": np.array([-2, 1, 3]),   # 보기 4
}

# 각 후보벡터에 대해 직교여공간의 원소인지 아닌지 판별
for label, v in candidates.items():

  # w1, w2 외의 내적 계산
  # <v, w1> = 0이고, <v, w2> = 0이면, v는 직교여공간 정의를 만족한다
  dot1 = np.dot(v, w1)  # <v, w1>
  dot2 = np.dot(v, w2)  # <v, w2>

  # 두 내적이 모두 0인지 확인 => True면 직교여공간의 원소
  is_perp = (dot1 == 0 and dot2 == 0)

  # 결과 출력
  print(f"v = {label}")
  print(f"  <v, w1> = {dot1},  <v, w2> = {dot2}")
  print(f"  W⊥ 원소 여부: {' YES' if is_perp else ' NO'}")
  print()


v = (2,1,0)
  <v, w1> = 2,  <v, w2> = 3
  W⊥ 원소 여부:  NO

v = (0,1,0)
  <v, w1> = 0,  <v, w2> = 1
  W⊥ 원소 여부:  NO

v = (0,0,1)
  <v, w1> = 0,  <v, w2> = 0
  W⊥ 원소 여부:  YES

v = (-2,1,3)
  <v, w1> = -2,  <v, w2> = -1
  W⊥ 원소 여부:  NO



# [퀴즈2] 행렬의 Rank

## 풀이

**주어진 조건:**
- $a = (1, 2, 3)$ → 행벡터 ($1 \times 3$ 행렬)
- $b = (2, 4, -2)$ → 행벡터 ($1 \times 3$ 행렬)

**$a^\top b$ 계산:**

$a^\top$은 $a$의 전치행렬이므로 $3 \times 1$ 열벡터, $b$는 $1 \times 3$ 행벡터입니다.

$$a^\top b = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix} \begin{pmatrix} 2 & 4 & -2 \end{pmatrix} = \begin{pmatrix} 2 & 4 & -2 \\ 4 & 8 & -4 \\ 6 & 12 & -6 \end{pmatrix}$$

이 행렬은 $3 \times 3$ 행렬입니다.

**rank 계산:**

강의자료 p.45에 따르면, rank는 행벡터들이 span하는 공간의 차원입니다.

행벡터들을 보면:
- 행1: $(2, 4, -2) = 2 \cdot (1, 2, -1)$
- 행2: $(4, 8, -4) = 4 \cdot (1, 2, -1)$
- 행3: $(6, 12, -6) = 6 \cdot (1, 2, -1)$

세 행벡터 모두 $(1, 2, -1)$의 스칼라 배이므로 **모두 일차종속**입니다. 단, 영벡터는 아닙니다.

따라서 $\text{rank}(a^\top b) = 1$

---

**정답: ③ 1**

---


각 행이 $(1,2,-1)$의 배수이므로 rank = **1**입니다.

In [5]:
# 다중공선성 : 중복되는 변수가 많다
# 변수가 3개 존재함
# Rank 1이 나옴
# => 독립적인 정보는 1개가 있음
# 나머지 2개는 중복된 정보를 함의하고 있다

import numpy as np
a = np.array([[1, 2, 3]])   # 1X3
b = np.array([[2, 4, -2]])  # 1X3

M = a.T @ b
print(M)

rank = np.linalg.matrix_rank(M)
print(rank)

[[ 2  4 -2]
 [ 4  8 -4]
 [ 6 12 -6]]
1


# [퀴즈3] 역행렬

## 풀이

**주어진 행렬:**
$$A = \begin{pmatrix} 3 & 1 \\ 2 & 1 \end{pmatrix}$$

**역행렬 공식 (강의자료 p.69):**

$$A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$$이면

$$A^{-1} = \frac{1}{ad - bc}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}$$

**행렬식(det) 계산:**

$$\det(A) = (3)(1) - (1)(2) = 3 - 2 = 1$$

$\det(A) = 1 \neq 0$이므로 역행렬이 존재합니다.

**역행렬 계산:**

$$A^{-1} = \frac{1}{1}\begin{pmatrix} 1 & -1 \\ -2 & 3 \end{pmatrix} = \begin{pmatrix} 1 & -1 \\ -2 & 3 \end{pmatrix}$$

**검증:**

$$AA^{-1} = \begin{pmatrix} 3 & 1 \\ 2 & 1 \end{pmatrix}\begin{pmatrix} 1 & -1 \\ -2 & 3 \end{pmatrix} = \begin{pmatrix} 3-2 & -3+3 \\ 2-2 & -2+3 \end{pmatrix} = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix} = I \checkmark$$

---

**정답: ① $A^{-1} = \begin{pmatrix} 1 & -1 \\ -2 & 3 \end{pmatrix}$**

---


In [7]:
import numpy as np

A = np.array([[3, 1], [2, 1]])
A_inv = np.linalg.inv(A)
print(A_inv)


[[ 1. -1.]
 [-2.  3.]]


# [퀴즈4] 행렬식

## 풀이

**주어진 행렬식:**

$$\det\begin{pmatrix} x & 1 & 1 \\ 1 & x & 1 \\ 1 & 1 & x \end{pmatrix}$$

**1행으로 여인수 전개 (강의자료 p.56):**

$$= x\begin{vmatrix} x & 1 \\ 1 & x \end{vmatrix} - 1\begin{vmatrix} 1 & 1 \\ 1 & x \end{vmatrix} + 1\begin{vmatrix} 1 & x \\ 1 & 1 \end{vmatrix}$$

**각 $2\times2$ 행렬식 계산:**

$$\begin{vmatrix} x & 1 \\ 1 & x \end{vmatrix} = x^2 - 1$$

$$\begin{vmatrix} 1 & 1 \\ 1 & x \end{vmatrix} = x - 1$$

$$\begin{vmatrix} 1 & x \\ 1 & 1 \end{vmatrix} = 1 - x$$

**대입:**

$$= x(x^2 - 1) - 1(x - 1) + 1(1 - x)$$

$$= x^3 - x - x + 1 + 1 - x$$

$$= x^3 - 3x + 2$$

---

**검증 (x=1 대입):**

두 행이 같아지면 det=0이어야 합니다. $x=1$이면 모든 행이 $(1,1,1)$로 같으므로 $\det = 0$.

$1^3 - 3(1) + 2 = 1 - 3 + 2 = 0$ ✓


---

**정답: ① $x^3 - 3x + 2$**

In [11]:
import numpy as np
from sympy import symbols, Matrix, det, expand

x = symbols('x')
A = Matrix([[x, 1, 1],
            [1, x, 1],
            [1, 1, x]])

result = expand(det(A))
result

x**3 - 3*x + 2

# [퀴즈5] 고윳값 계산

# 풀이

## 문제 분석

행렬 $A = \begin{pmatrix} 3 & 1 \\ 1 & 3 \end{pmatrix}$의 고유벡터가 주어질 때, 대응하는 고유값을 구합니다.

- $v_1 = \begin{pmatrix} 1 \\ 1 \end{pmatrix}$
- $v_2 = \begin{pmatrix} -1 \\ 1 \end{pmatrix}$

---

## 풀이 과정

### Step 1: 특성방정식으로 고유값 구하기

강의자료 p.15의 **정의 6.2**에 따라, 고유값은 특성방정식 $\det(\lambda I - A) = 0$을 풀어 구합니다.

$$\det(\lambda I - A) = \det\begin{pmatrix} \lambda - 3 & -1 \\ -1 & \lambda - 3 \end{pmatrix} = 0$$

$$(\lambda - 3)^2 - 1 = 0$$

$$\lambda^2 - 6\lambda + 9 - 1 = 0$$

$$\lambda^2 - 6\lambda + 8 = 0$$

$$(\lambda - 4)(\lambda - 2) = 0$$

따라서 고유값은 $\lambda = 4$ 또는 $\lambda = 2$

---

### Step 2: $v_1$에 대응하는 고유값 확인

강의자료 p.8의 **정의 6.1** — $Av = \lambda v$를 만족하는 $\lambda$가 고유값입니다.

$$Av_1 = \begin{pmatrix} 3 & 1 \\ 1 & 3 \end{pmatrix}\begin{pmatrix} 1 \\ 1 \end{pmatrix} = \begin{pmatrix} 3 \cdot 1 + 1 \cdot 1 \\ 1 \cdot 1 + 3 \cdot 1 \end{pmatrix} = \begin{pmatrix} 4 \\ 4 \end{pmatrix} = 4\begin{pmatrix} 1 \\ 1 \end{pmatrix} = 4v_1$$

$$\therefore \boxed{\lambda_1 = 4}$$

---

### Step 3: $v_2$에 대응하는 고유값 확인

$$Av_2 = \begin{pmatrix} 3 & 1 \\ 1 & 3 \end{pmatrix}\begin{pmatrix} -1 \\ 1 \end{pmatrix} = \begin{pmatrix} 3 \cdot (-1) + 1 \cdot 1 \\ 1 \cdot (-1) + 3 \cdot 1 \end{pmatrix} = \begin{pmatrix} -2 \\ 2 \end{pmatrix} = 2\begin{pmatrix} -1 \\ 1 \end{pmatrix} = 2v_2$$

$$\therefore \boxed{\lambda_2 = 2}$$

---

## 정답 정리

- $v_1 = \begin{pmatrix}1\\1\end{pmatrix}$ → $\lambda = 4$
- $v_2 = \begin{pmatrix}-1\\1\end{pmatrix}$ → $\lambda = 2$

---


> **참고** (강의자료 p.30, 정리 6.8): $A$는 대칭행렬($A^\top = A$)이므로 서로 다른 고유값에 대응하는 고유벡터 $v_1, v_2$는 직교합니다. 실제로 $v_1^\top v_2 = (1)(-1) + (1)(1) = 0$ ✓

In [14]:
import numpy as np

# 행렬과 고유벡터 각각 정의
A = np.array([[3, 1], [1, 3]])

v1 = np.array([1, 1])
v2 = np.array([-1, 1])

# 검증 : 수동으로 구하기
Av1 = A @ v1
Av2 = A @ v2
print(Av2)

# 고윳값 추출 : (AV)[0] / v[0] (v[i] 0이 아니다 성분 사용)
lambda1 = Av1[0] / v1[0]
lambda2 = Av2[1] / v1[1]

# numpy 내장 함수로 검증
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"고윳값 = {sorted(eigenvalues, reverse=True)}")

[-2  2]
고윳값 = [np.float64(4.0), np.float64(2.0)]


# [퀴즈6] 고유벡터 계산

# 풀이

## 문제

$A = \begin{pmatrix} 4 & 2 \\ 3 & 5 \end{pmatrix}$에서 $\lambda_1 = 7$, $\lambda_2 = 2$에 대응하는 고유벡터를 구하시오.

---

## Step 1: $\lambda_1 = 7$일 때 고유벡터

$(\lambda I - A)v = 0$, 즉 $(7I - A)v = 0$

$$\begin{pmatrix} 7-4 & -2 \\ -3 & 7-5 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} 3 & -2 \\ -3 & 2 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \end{pmatrix}$$

1행: $3x - 2y = 0 \Rightarrow y = \dfrac{3}{2}x$

$x = 2$로 놓으면 $y = 3$

$$\therefore v_1 = \begin{pmatrix} 2 \\ 3 \end{pmatrix}$$

**검증:**
$$Av_1 = \begin{pmatrix}4&2\\3&5\end{pmatrix}\begin{pmatrix}2\\3\end{pmatrix} = \begin{pmatrix}8+6\\6+15\end{pmatrix} = \begin{pmatrix}14\\21\end{pmatrix} = 7\begin{pmatrix}2\\3\end{pmatrix} \checkmark$$

---

## Step 2: $\lambda_2 = 2$일 때 고유벡터

$(2I - A)v = 0$

$$\begin{pmatrix} 2-4 & -2 \\ -3 & 2-5 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} -2 & -2 \\ -3 & -3 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \end{pmatrix}$$

1행: $-2x - 2y = 0 \Rightarrow y = -x$

$x = 1$로 놓으면 $y = -1$

$$\therefore v_2 = \begin{pmatrix} 1 \\ -1 \end{pmatrix}$$

**검증:**
$$Av_2 = \begin{pmatrix}4&2\\3&5\end{pmatrix}\begin{pmatrix}1\\-1\end{pmatrix} = \begin{pmatrix}4-2\\3-5\end{pmatrix} = \begin{pmatrix}2\\-2\end{pmatrix} = 2\begin{pmatrix}1\\-1\end{pmatrix} \checkmark$$

---

## 정답 정리

- $\lambda_1 = 7$ → $v = \begin{pmatrix}2\\3\end{pmatrix}$
- $\lambda_2 = 2$ → $v = \begin{pmatrix}1\\-1\end{pmatrix}$

---


In [21]:
import numpy as np

A = np.array([[4, 2], [3, 5]])

# 고유벡터 직접 계산
for lam, label in [(7, "λ1=7"), (2, "λ2=2")]:
  print(lam, label)
  M = lam * np.eye(2) - A # (λ | - A)
  # print(M)

  # null space 구하기 : SVD 활용
  _, _, Vt = np.linalg.svd(M)
  v = Vt[-1]  # 마지막행 = 최소 특이값에 대응
  v = v / v[np.abs(v).argmax()] # 최대 성분으로 정규화
  print(v)
  print(f"{label} : v = {v}")
  print(f" 검증 Av = {A @ v}, λ v = {lam * v}\n")

7 λ1=7
[0.66666667 1.        ]
λ1=7 : v = [0.66666667 1.        ]
 검증 Av = [4.66666667 7.        ], λ v = [4.66666667 7.        ]

2 λ2=2
[-1.  1.]
λ2=2 : v = [-1.  1.]
 검증 Av = [-2.  2.], λ v = [-2.  2.]



# [퀴즈] 행렬의 대각화

## 풀이

**Step 1. 특성방정식으로 고윳값 계산**

$$\det(\lambda I - A) = \det\begin{pmatrix}\lambda-3&-1\\-1&\lambda-3\end{pmatrix} = (\lambda-3)^2 - 1 = \lambda^2 - 6\lambda + 8 = (\lambda-4)(\lambda-2) = 0$$

고윳값: $\lambda_1 = 4$, $\lambda_2 = 2$

---

**Step 2. 고유벡터 계산**

**$\lambda_1 = 4$일 때**, $(A - 4I)v = 0$:

$$\begin{pmatrix}-1&1\\1&-1\end{pmatrix}\begin{pmatrix}x\\y\end{pmatrix} = \begin{pmatrix}0\\0\end{pmatrix}$$

$$-x + y = 0 \implies x = y$$

$$\therefore v_1 = \begin{pmatrix}1\\1\end{pmatrix}$$

**$\lambda_2 = 2$일 때**, $(A - 2I)v = 0$:

$$\begin{pmatrix}1&1\\1&1\end{pmatrix}\begin{pmatrix}x\\y\end{pmatrix} = \begin{pmatrix}0\\0\end{pmatrix}$$

$$x + y = 0 \implies y = -x$$

$$\therefore v_2 = \begin{pmatrix}1\\-1\end{pmatrix}$$

---

**Step 3. 대각화**

$$P = [v_1, v_2] = \begin{pmatrix}1&1\\1&-1\end{pmatrix}, \quad D = \begin{pmatrix}4&0\\0&2\end{pmatrix}$$

$$A = PDP^{-1}$$

---

**Step 4. $A^{100}$ 계산**

$$A^{100} = PD^{100}P^{-1} = P\begin{pmatrix}4^{100}&0\\0&2^{100}\end{pmatrix}P^{-1}$$

문제의 형태 $P\begin{pmatrix}X&1\\1&Y\end{pmatrix}P^{-1}$와 대응시키면:

$$\boxed{X = 4^{100}, \quad Y = 2^{100}}$$

---




In [22]:
import numpy as np

A = np.array([[3, 1], [1, 3]], dtype=float)

# 고윳값, 고유벡터 계산
eigenvalues, P = np.linalg.eig(A)
print("고윳값:", eigenvalues)          # [4. 2.]
print("고유벡터 행렬 P:\n", P)

# A = PDP^{-1} 검증
P_inv = np.linalg.inv(P)
D = np.diag(eigenvalues)
print("PDP^{-1} == A ?", np.allclose(P @ D @ P_inv, A))

# A^100 계산
D_100 = np.diag(eigenvalues ** 100)
A_100 = P @ D_100 @ P_inv

print("\nX = 4^100 =", int(4**100))
print("Y = 2^100 =", int(2**100))

고윳값: [4. 2.]
고유벡터 행렬 P:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
PDP^{-1} == A ? True

X = 4^100 = 1606938044258990275541962092341162602522202993782792835301376
Y = 2^100 = 1267650600228229401496703205376
